apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/stsewang17/platform-engineering.git
    targetRevision: HEAD
    path: platform-engineering/infrastructure/gcp/gcs
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
