# Adds VPC/Network support to Crossplane
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-gcp-compute
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-compute:v2.4.0
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
